# Generated by Django 4.2.30 on 2026-07-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datagen_base_seed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_command',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_positions_per_chunk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_total_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DatagenChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('position_count', models.BigIntegerField()),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('bytes', models.BigIntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datagen_chunks', to='OpenBench.machine')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datagen_chunks', to='OpenBench.test')),
            ],
            options={
                'ordering': ['idx'],
            },
        ),
        migrations.AddConstraint(
            model_name='datagenchunk',
            constraint=models.UniqueConstraint(fields=('test', 'idx'), name='unique_datagen_test_chunk'),
        ),
    ]
