# Generated by Django 4.2.30 on 2026-07-15 22:16

from django.db import migrations, models
from django.db.models import Count, Sum


def backfill_datagen_progress(apps, schema_editor):
    Test = apps.get_model('OpenBench', 'Test')
    DatagenChunk = apps.get_model('OpenBench', 'DatagenChunk')

    generic_ids = Test.objects.filter(
        test_mode='DATAGEN',
    ).exclude(datagen_command='').values_list('id', flat=True)
    for test_id in generic_ids.iterator():
        progress = DatagenChunk.objects.filter(
            test_id=test_id,
            status='COMPLETED',
        ).aggregate(chunks=Count('id'), positions=Sum('position_count'))
        Test.objects.filter(pk=test_id).update(
            datagen_completed_chunks=progress['chunks'] or 0,
            games=progress['positions'] or 0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0002_test_datagen_base_seed_test_datagen_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='datagen_completed_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_datagen_progress, migrations.RunPython.noop),
    ]
