# Generated by Django 4.2.30 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0003_datagen_completed_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='games',
            field=models.BigIntegerField(default=0),
        ),
    ]
