# Generated by Django 4.2.30 on 2026-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBench', '0004_test_games_bigint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
