# Generated by Django 4.2.30 on 2026-07-16 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashlib
import json
import string


def backfill_producer_reservations(apps, schema_editor):
    Test = apps.get_model('OpenBench', 'Test')
    Chunk = apps.get_model('OpenBench', 'DatagenChunk')
    Artifact = apps.get_model('OpenBench', 'DatagenProducerArtifact')
    Build = apps.get_model('OpenBench', 'DatagenProducerBuild')
    Quota = apps.get_model('OpenBench', 'DatagenProducerQuota')
    OwnerQuota = apps.get_model('OpenBench', 'DatagenProducerOwnerQuota')
    User = apps.get_model('auth', 'User')

    for test in Test.objects.filter(test_mode='DATAGEN').exclude(datagen_command=''):
        try:
            required = any(
                name == 'PRODUCER_SHA256'
                for _literal, name, _format_spec, _conversion
                in string.Formatter().parse(test.datagen_command)
            )
        except ValueError:
            required = False
        contract = json.dumps({
            'command': test.datagen_command,
            'producer_artifact_required': required,
            'protocol': 39,
            'schema': 'openbench-datagen-producer-v39',
        }, sort_keys=True, separators=(',', ':')).encode('utf-8')
        test.datagen_producer_required = required
        test.datagen_producer_contract_sha256 = hashlib.sha256(contract).hexdigest()
        test.save(update_fields=[
            'datagen_producer_required',
            'datagen_producer_contract_sha256',
        ])

    # Existing v39 rows were authenticated at ingestion, but filesystem bytes
    # may have drifted since. Fail closed until the first explicit scrub.
    Artifact.objects.all().update(state='UNVERIFIED', last_verified=None)
    quota, _ = Quota.objects.get_or_create(key='global')
    quota.artifact_count = Artifact.objects.count()
    quota.reserved_bytes = sum(
        Artifact.objects.values_list('bytes', flat=True)
    )
    quota.save(update_fields=['artifact_count', 'reserved_bytes'])

    owner_totals = {}
    for test in Test.objects.all():
        owner = User.objects.filter(username=test.author).first()
        if owner is None:
            continue
        seen = set()
        bindings = (
            Chunk.objects.filter(test_id=test.id)
            .exclude(producer_sha256='')
            .values_list(
                'producer_sha256', 'producer_bytes', 'producer_commit'
            )
            .distinct()
        )
        for producer_sha, producer_bytes, producer_commit in bindings:
            artifact = Artifact.objects.filter(
                sha256=producer_sha,
                bytes=producer_bytes,
            ).first()
            if artifact is None:
                continue
            build, created = Build.objects.get_or_create(
                test_id=test.id,
                artifact_id=artifact.id,
                defaults={
                    'owner_id': owner.id,
                    'commit': producer_commit,
                    'contract_sha256': test.datagen_producer_contract_sha256,
                },
            )
            Chunk.objects.filter(
                test_id=test.id,
                producer_sha256=producer_sha,
                producer_bytes=producer_bytes,
                producer_commit=producer_commit,
            ).update(producer_build_id=build.id)
            if created:
                seen.add(artifact.id)
        if seen:
            byte_count = sum(
                Artifact.objects.get(pk=artifact_id).bytes
                for artifact_id in seen
            )
            test.datagen_producer_build_count = len(seen)
            test.datagen_producer_build_bytes = byte_count
            test.save(update_fields=[
                'datagen_producer_build_count',
                'datagen_producer_build_bytes',
            ])
            count, total = owner_totals.get(owner.id, (0, 0))
            owner_totals[owner.id] = (count + len(seen), total + byte_count)

    for artifact in Artifact.objects.all():
        artifact.reference_count = Build.objects.filter(artifact_id=artifact.id).count()
        artifact.save(update_fields=['reference_count'])
    for owner_id, (count, byte_count) in owner_totals.items():
        OwnerQuota.objects.update_or_create(
            owner_id=owner_id,
            defaults={'build_count': count, 'reserved_bytes': byte_count},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('OpenBench', '0005_datagen_producer_artifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatagenProducerBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(max_length=40)),
                ('contract_sha256', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatagenProducerOwnerQuota',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='datagen_producer_quota', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('build_count', models.BigIntegerField(default=0)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatagenProducerQuota',
            fields=[
                ('key', models.CharField(default='global', max_length=16, primary_key=True, serialize=False)),
                ('artifact_count', models.BigIntegerField(default=0)),
                ('reserved_bytes', models.BigIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='datagenproducerartifact',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datagenproducerartifact',
            name='reference_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datagenproducerartifact',
            name='staging_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='datagenproducerartifact',
            name='state',
            field=models.CharField(default='STAGING', max_length=16),
        ),
        migrations.AddField(
            model_name='datagenproducerartifact',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_producer_build_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_producer_build_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_producer_contract_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='test',
            name='datagen_producer_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerartifact',
            constraint=models.CheckConstraint(check=models.Q(('bytes__gt', 0)), name='datagen_producer_bytes_positive'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerartifact',
            constraint=models.CheckConstraint(check=models.Q(('reference_count__gte', 0)), name='datagen_producer_refcount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerartifact',
            constraint=models.CheckConstraint(check=models.Q(('state__in', ['STAGING', 'AVAILABLE', 'CORRUPT', 'UNVERIFIED'])), name='datagen_producer_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerquota',
            constraint=models.CheckConstraint(check=models.Q(('key', 'global')), name='datagen_global_quota_singleton'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerquota',
            constraint=models.CheckConstraint(check=models.Q(('artifact_count__gte', 0)), name='datagen_global_artifacts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerquota',
            constraint=models.CheckConstraint(check=models.Q(('reserved_bytes__gte', 0)), name='datagen_global_bytes_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerownerquota',
            constraint=models.CheckConstraint(check=models.Q(('build_count__gte', 0)), name='datagen_owner_builds_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerownerquota',
            constraint=models.CheckConstraint(check=models.Q(('reserved_bytes__gte', 0)), name='datagen_owner_bytes_nonnegative'),
        ),
        migrations.AddField(
            model_name='datagenproducerbuild',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_builds', to='OpenBench.datagenproducerartifact'),
        ),
        migrations.AddField(
            model_name='datagenproducerbuild',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datagen_producer_builds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datagenproducerbuild',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datagen_producer_builds', to='OpenBench.test'),
        ),
        migrations.AddField(
            model_name='datagenchunk',
            name='producer_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='OpenBench.datagenproducerbuild'),
        ),
        migrations.AddConstraint(
            model_name='datagenproducerbuild',
            constraint=models.UniqueConstraint(fields=('test', 'artifact'), name='unique_datagen_campaign_producer'),
        ),
        migrations.RunPython(backfill_producer_reservations, noop_reverse),
    ]
