"""
Django settings for OpenSite project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

from django.core.exceptions import ImproperlyConfigured

from .atomicdb_identity import (
    AtomicDBIdentityError,
    split_activation_required,
    validate_database_lineage_path,
)
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
# Public deployments MUST set both env vars; the fallbacks are for local dev
SECRET_KEY = os.environ.get(
    'OPENBENCH_SECRET_KEY', '@!zw2l8til1(0eb_nk+1w!(n78gqm&u)s)_v7#k6iseia@g9q0')
DEBUG = os.environ.get('OPENBENCH_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

# The public web goes through an HTTPS tunnel in front of runserver; Django's
# CSRF origin check needs the tunnel origin trusted or every login/form POST
# 403s. Comma-separated env override; the default trusts TryCloudflare quick
# tunnels (their subdomain rotates on every tunnel restart).
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get('OPENBENCH_TRUSTED_ORIGINS',
                              'https://belzedar.duckdns.org,https://*.trycloudflare.com').split(',') if o]

# Trust X-Forwarded-Proto only when the application is known to sit behind a
# proxy that strips the client-supplied header and sets its own value.  DATAGEN
# producer/manifest HTTP Basic authentication relies on request.is_secure().
if os.environ.get('OPENBENCH_TRUST_X_FORWARDED_PROTO', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

HTML_MINIFY   = True
APPEND_SLASH  = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

SETTINGS_DIR  = os.path.dirname(__file__)
PROJECT_PATH  = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH  = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'Templates')

MEDIA_URL  = '/Media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Media')

# Conquest Map snapshots are observational, immutable inputs to the public
# read-only API.  The builder publishes this file with os.replace(); web
# requests never fall back to traversing the live solver database.
ATOMICDB_MAP_SNAPSHOT_PATH = os.environ.get(
    'ATOMICDB_MAP_SNAPSHOT_PATH',
    os.path.join(MEDIA_ROOT, 'atomicdb', 'conquest-map-v1.json.gz'),
)

# AtomicDB authoritative tablebase verification.  Paths use the same
# semicolon-separated convention as Client/atomicdb_worker.py --syzygy.
ATOMICDB_TB_PATHS = [
    path for path in os.environ.get(
        'ATOMICDB_TB_PATHS', '/opt/openbench/atomic-syzygy-345/'
    ).split(';') if path
]
ATOMICDB_TB_TRUSTED = [
    username.strip() for username in os.environ.get(
        'ATOMICDB_TB_TRUSTED', 'belzedar'
    ).split(',') if username.strip()
]

# Identidad CONGELADA del enunciado que AtomicDB prueba.  No es una opcion de
# despliegue: cambiarla cambia el teorema, y todo cierre decisivo existente
# quedaria referido a otras reglas.  La semantica completa esta en el
# docstring de atomicdb/logic.py.
ATOMICDB_RULESET_ID = 'atomic-fide-claim-v1'
# Regla fresh-context: un hijo decisivo solo sostiene el cierre de su padre a
# traves de una arista tranquila si le queda margen de reloj.  Endurece los
# cierres NUEVOS; apagarla es volver al comportamiento anterior a P1b.
ATOMICDB_FRESH_CONTEXT = os.environ.get(
    'ATOMICDB_FRESH_CONTEXT', 'True').lower() not in ('0', 'false', 'no')
# Selector de trabajo: 'regret' (Dijkstra de interes, por defecto) o 'pn'
# (descenso df-pn del gestor de prueba).
ATOMICDB_SELECTOR = os.environ.get('ATOMICDB_SELECTOR', 'regret')
# Salida de emergencia: recalcular prioridades dentro de la request del worker
# si el servicio refresh_selector no esta corriendo.
ATOMICDB_INLINE_SELECTOR = os.environ.get(
    'ATOMICDB_INLINE_SELECTOR', '').lower() in ('1', 'true', 'yes')
# Selector ACOTADO (P1.6): Dijkstra por lotes con horizonte de poda en vez de
# la foto del grafo entero en RAM.  APAGADO por defecto y no por prudencia
# generica: v1 es lo que esta desplegado y medido, y este conmutador no se
# toca hasta que ``selector_shadow`` publique el Jaccard y el Kendall del
# top-1000 sobre la base viva.  Antes de encenderlo hay que haber aplicado la
# migracion 0036 y corrido ``backfill_reachable`` en CADA base — sin sembrar,
# la columna le pone precio de cajetin suelto a media base
# (§ docs/selector-incremental.md).
ATOMICDB_SELECTOR_V2 = os.environ.get(
    'ATOMICDB_SELECTOR_V2', '').lower() in ('1', 'true', 'yes')
# Pasadas INCREMENTALES del selector: repuntuar la bola y lo que se movio, en
# vez del universo UNKNOWN entero.  ENCENDIDO por defecto, al reves que sus
# vecinos de aqui y a proposito: aquellos estrenan comportamiento y tienen que
# ganarse el sitio, este no cambia ni un numero — misma formula, mismos
# precios, mismas lapidas — solo deja de reescribir filas que nadie ha tocado,
# y es lo que esta desplegado y medido.  La linea existe para poder APAGARLO
# desde el entorno: cualquier cosa que huela a "no" devuelve la pasada completa
# con un reinicio y sin desplegar codigo, que es lo unico que se le pide a una
# salida de emergencia.
ATOMICDB_SELECTOR_DELTA = os.environ.get(
    'ATOMICDB_SELECTOR_DELTA', '').lower() not in ('0', 'false', 'no')
# Directorio de estado del selector (en el servidor, el ``StateDirectory=``
# de systemd).  Hoy guarda una sola cosa: el marcador de la ultima pasada
# completada, para que un reinicio del servicio no fuerce una pasada completa
# de horas.  Vacio = sin persistencia (tests, desarrollo): cada proceso lleva
# su ventana en memoria, como siempre.
ATOMICDB_STATE_DIR = os.environ.get('ATOMICDB_STATE_DIR', '')
# Brazos adversariales del explorador (reparacion de dn y solves F0 sobre
# afirmaciones fragiles de mate).  APAGADOS por defecto a proposito: el
# paquete existe para medir si mejoran los cierres, y esa medida necesita un
# snapshot "antes" tomado con el codigo desplegado y los brazos quietos.  Se
# encienden cuando ese snapshot esta en la tabla.
ATOMICDB_ADVERSARIAL = os.environ.get(
    'ATOMICDB_ADVERSARIAL', '').lower() in ('1', 'true', 'yes')
# Breadth-swap (experimento Torom, 29-jul-2026): la peticion sobre un nodo YA
# analizado se convierte en expansion de frontera un ply mas abajo en vez de
# comprar el siguiente peldano profundo. Medido sobre 800 revisitas reales:
# con un ply de hijos a 128M el veredicto coincide con el re-search profundo
# el 96-99% de las veces; la profundidad queda para disputas, banda de mate
# y frontera saturada. APAGADO por defecto: se enciende via drop-in de
# systemd cuando el propietario lo decida, y apagarlo restaura la escalera
# clasica sin residuo.
ATOMICDB_BREADTH_SWAP = os.environ.get(
    'ATOMICDB_BREADTH_SWAP', '').lower() in ('1', 'true', 'yes')
# Puerta doble de exploracion (idea de Wolfram, 30-jul-2026): un nodo se
# explora PARA RESOLVER solo cuando el eval del motor y un estimador
# INDEPENDIENTE de coste de resolver (atomicdb/solve_estimate.py) coinciden en
# que es prometedor.  Con la puerta encendida, la inicializacion de hojas del
# gestor de prueba multiplica el pn por un factor 1..K creciente con la
# molestia estimada, de modo que el descenso df-pn deja de perforar finales
# tediosos aunque el eval diga +1200.  APAGADA por defecto: enciende via
# drop-in de systemd, y apagarla restaura los numeros historicos sin residuo
# (los pn de hoja se recalculan en la siguiente pasada de mantenimiento).
ATOMICDB_SOLVE_GATE = os.environ.get(
    'ATOMICDB_SOLVE_GATE', '').lower() in ('1', 'true', 'yes')
# Descensos que ARRANCAN en la raiz de una campana ACTIVE (5-ago-2026).  Con
# el selector en 'pn' el trabajo lo reparte el descenso df-pn, que no lee
# ``Position.priority`` — donde vivia el unico peso de las campanas — asi que
# una campana votada ganaba la columna y no recibia ni una tarea.  Como mucho
# el 35% de los descensos, repartido entre las ACTIVE por ``ln(1+votos)``; el
# resto del descenso no cambia (§ docs/solver-allocation.md).  ENCENDIDO por
# defecto, como ``ATOMICDB_SELECTOR_DELTA`` y por lo mismo: no estrena motor,
# mueve el punto de arranque de una fraccion acotada de los descensos, y
# apagarlo desde el entorno devuelve la cola de siempre con un reinicio.
ATOMICDB_CAMPAIGN_DESCENT = os.environ.get(
    'ATOMICDB_CAMPAIGN_DESCENT', '').lower() not in ('0', 'false', 'no')
# Presupuesto MINIMO para los hermanos de un hijo ya PROBADO bajo un nodo OR.
# Generaliza el carve-out del mate corto a distancia desconocida: si el
# atacante ya tiene una victoria probada en ese nodo, sus demas jugadas no le
# deben nada a la prueba y no compran el peldano entero de la escalera.  No
# toca nodos AND, donde hay que refutar TODAS las respuestas.  ENCENDIDO por
# defecto; apagarlo devuelve la escalera clasica sin residuo, porque esto solo
# elige un presupuesto y no escribe nada en la base.
ATOMICDB_OR_CLAMP = os.environ.get(
    'ATOMICDB_OR_CLAMP', '').lower() not in ('0', 'false', 'no')

INSTALLED_APPS = [
    'atomicdb',
    'OpenBench',
    'OpenBench.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves /static/ with DEBUG=False (the overridden runserver does not
    # accept --insecure); USE_FINDERS avoids needing collectstatic
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'OpenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                # Zona de identidad de AtomicDB (sesion + campana de avisos).
                # Se corta sola fuera de /atomicdb/, asi que para las paginas
                # de OpenBench es una comparacion de cadenas y nada mas.
                'atomicdb.notifications.identity',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # OB datagen + AtomicDB share this file: wait out writer bursts
        # instead of raising "database is locked" (DB itself runs WAL)
        'OPTIONS': {'timeout': 30},
    }
}

# Production and CI can exercise the row-lock/CAS path on PostgreSQL without
# maintaining a second settings module. SQLite remains the zero-config local
# default used by existing installations.
if os.environ.get('OPENBENCH_POSTGRES_DB'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['OPENBENCH_POSTGRES_DB'],
        'USER': os.environ.get('OPENBENCH_POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('OPENBENCH_POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('OPENBENCH_POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('OPENBENCH_POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 0,
    }

ATOMICDB_DATABASE_ALIAS = 'default'
# AtomicDB on Postgres.  Inert without OPENBENCH_ATOMICDB_POSTGRES_DB: with the
# variable unset, everything below behaves exactly as it did on SQLite, so
# deploying this code changes nothing until the migration window arrives.
#
# When it IS set, the SQLite split identity does not apply — a receipt is a
# statement about a SQLite file — so the whole activation block is skipped and
# the alias points at Postgres instead.  See Documentation/postgres-migration.md
# for the runbook, including why the two databases move separately.
_atomicdb_postgres_db = os.environ.get('OPENBENCH_ATOMICDB_POSTGRES_DB',
                                       '').strip()
_explicit_atomicdb_path = os.environ.get('OPENBENCH_ATOMICDB_PATH', '').strip()
_durable_atomicdb_path = os.path.join(BASE_DIR, 'atomicdb.sqlite3')
_atomicdb_path = _explicit_atomicdb_path or _durable_atomicdb_path
_atomicdb_path = os.path.realpath(os.path.abspath(
    os.path.expanduser(_atomicdb_path)))
_atomicdb_receipt_path = _atomicdb_path + '.split-receipt.json'
_atomicdb_exists = os.path.isfile(_atomicdb_path)
_atomicdb_receipt_exists = os.path.isfile(_atomicdb_receipt_path)
_atomicdb_requested = bool(_explicit_atomicdb_path)

if _atomicdb_postgres_db:
    _activate_atomicdb_split = False
else:
    try:
        _activate_atomicdb_split = split_activation_required(
            explicit_requested=_atomicdb_requested,
            database_exists=_atomicdb_exists,
            receipt_exists=_atomicdb_receipt_exists,
        )
    except AtomicDBIdentityError as error:
        raise ImproperlyConfigured(str(error)) from error

if _atomicdb_postgres_db:
    DATABASES['atomicdb'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _atomicdb_postgres_db,
        'USER': os.environ.get('OPENBENCH_ATOMICDB_POSTGRES_USER',
                               os.environ.get('OPENBENCH_POSTGRES_USER',
                                              'postgres')),
        'PASSWORD': os.environ.get('OPENBENCH_ATOMICDB_POSTGRES_PASSWORD',
                                   os.environ.get(
                                       'OPENBENCH_POSTGRES_PASSWORD', '')),
        'HOST': os.environ.get('OPENBENCH_ATOMICDB_POSTGRES_HOST',
                               os.environ.get('OPENBENCH_POSTGRES_HOST',
                                              '127.0.0.1')),
        'PORT': os.environ.get('OPENBENCH_ATOMICDB_POSTGRES_PORT',
                               os.environ.get('OPENBENCH_POSTGRES_PORT',
                                              '5432')),
        # Persistent connections matter more here than for the web database:
        # the ingest processor and the selector service open one connection
        # each and hold it for their whole lifetime.
        'CONN_MAX_AGE': int(os.environ.get(
            'OPENBENCH_ATOMICDB_POSTGRES_CONN_MAX_AGE', '60')),
    }
    ATOMICDB_DATABASE_ALIAS = 'atomicdb'
elif _activate_atomicdb_split:
    if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
        _default_sqlite_path = os.path.realpath(os.path.abspath(
            os.path.expanduser(str(DATABASES['default']['NAME']))))
        if os.path.normcase(_atomicdb_path) == os.path.normcase(_default_sqlite_path):
            raise ImproperlyConfigured(
                'OPENBENCH_ATOMICDB_PATH must differ from the default SQLite database path')

    try:
        with open(_atomicdb_receipt_path, 'rb') as receipt_file:
            _atomicdb_receipt_bytes = receipt_file.read()
        _atomicdb_receipt, _atomicdb_lineage = \
            validate_database_lineage_path(
                _atomicdb_path, _atomicdb_receipt_bytes)
    except (OSError, AtomicDBIdentityError) as error:
        raise ImproperlyConfigured(
            'AtomicDB split identity validation failed: {}'.format(
                error)) from error

    DATABASES['atomicdb'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _atomicdb_path,
        'OPTIONS': {'timeout': 30},
    }
    ATOMICDB_DATABASE_ALIAS = 'atomicdb'

DATABASE_ROUTERS = ['OpenSite.db_routers.AtomicDBRouter']


# Caches
#
# Four readers share this: the short ``cache_page`` on the hot read views
# (home/map/method, and OpenBench's index), the lineage breadcrumbs behind
# every explore/goto render, the replayed route labels of the queue rows, and
# the public counters of the front page.
#
# WHY IT IS SHARED NOW.  The site runs FIVE gunicorn workers, and a
# per-process LocMemCache gives each of them its own copy of all of that.
# Three things were measured to be wrong with that, in rising order of cost:
# the same breadcrumb walk was paid five times; a visitor whose page entry
# existed on worker 3 missed it four requests out of five; and — the one that
# no ceiling could fix — a producer OUTSIDE the request path cannot publish
# into a cache that lives inside a web worker.  The front page's expensive
# counters are exactly that: full-table aggregates that belong on the
# selector service's timer, not in a visitor's request (§ atomicdb.metrics,
# refresh_selector).
#
# WHAT IT DOES NOT BUY.  No invalidation protocol: every entry here is
# public, derived, and expires on its own TTL, so a stale entry is at worst a
# number a minute old and never a wrong one.  Flushing the Redis database is
# still a legitimate emergency lever, and so is stopping Redis: the backend
# below falls back to the per-process cache this deployment used before, so
# an unreachable Redis costs the fleet its shared copy and nothing else
# (§ OpenSite.cache).
#
# The fallback ceiling is sized off the TTL, not off the tree: nothing
# survives two minutes, so it only has to cover the distinct positions a
# burst can touch in that window, and each worker sees roughly a fifth of
# them.  4000 is well past that.  It is also the memory bound — a breadcrumb
# entry is a few kB, and the rare 96-ply one about 10kB — so a saturated
# worker is tens of MB and the fleet stays in double digits.
REDIS_CACHE_URL = os.environ.get('OPENBENCH_REDIS_URL',
                                 'redis://127.0.0.1:6379/1')
# ``auto`` uses Redis and degrades on its own; ``locmem`` never dials it.
# The test suite forces ``locmem`` below: ``cache.clear()`` between tests is a
# FLUSHDB on Redis, and running the suite on the deployment box must not
# empty the cache the live site is serving from.
CACHE_BACKEND_CHOICE = os.environ.get('OPENBENCH_CACHE_BACKEND', 'auto')
RUNNING_TESTS = len(sys.argv) > 1 and sys.argv[1] == 'test'
if RUNNING_TESTS:
    CACHE_BACKEND_CHOICE = 'locmem'

_LOCMEM_CACHE = {
    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    'LOCATION': 'openbench-default',
    'OPTIONS': {'MAX_ENTRIES': 4000, 'CULL_FREQUENCY': 4},
}

if CACHE_BACKEND_CHOICE == 'locmem':
    CACHES = {'default': _LOCMEM_CACHE}
else:
    CACHES = {
        'default': {
            'BACKEND': 'OpenSite.cache.ResilientRedisCache',
            'LOCATION': REDIS_CACHE_URL,
            # Short socket timeouts on purpose: this is a loopback Redis, so
            # anything slower than this is a Redis that is not answering, and
            # a front page must find that out in milliseconds rather than
            # wait on a default timeout.
            'OPTIONS': {'socket_connect_timeout': 0.1, 'socket_timeout': 1.0},
            'FALLBACK_LOCATION': 'openbench-default',
            'FALLBACK_OPTIONS': {'MAX_ENTRIES': 4000, 'CULL_FREQUENCY': 4},
        },
    }


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
WHITENOISE_USE_FINDERS = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
