"""
Django settings for OpenSite project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
# Public deployments MUST set both env vars; the fallbacks are for local dev
SECRET_KEY = os.environ.get(
    'OPENBENCH_SECRET_KEY', '@!zw2l8til1(0eb_nk+1w!(n78gqm&u)s)_v7#k6iseia@g9q0')
DEBUG = os.environ.get('OPENBENCH_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

# The public web goes through an HTTPS tunnel in front of runserver; Django's
# CSRF origin check needs the tunnel origin trusted or every login/form POST
# 403s. Comma-separated env override; the default trusts TryCloudflare quick
# tunnels (their subdomain rotates on every tunnel restart).
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get('OPENBENCH_TRUSTED_ORIGINS',
                              'https://belzedar.duckdns.org,https://*.trycloudflare.com').split(',') if o]

# Trust X-Forwarded-Proto only when the application is known to sit behind a
# proxy that strips the client-supplied header and sets its own value.  DATAGEN
# producer/manifest HTTP Basic authentication relies on request.is_secure().
if os.environ.get('OPENBENCH_TRUST_X_FORWARDED_PROTO', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

HTML_MINIFY   = True
APPEND_SLASH  = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

SETTINGS_DIR  = os.path.dirname(__file__)
PROJECT_PATH  = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH  = os.path.abspath(PROJECT_PATH)
TEMPLATE_PATH = os.path.join(PROJECT_PATH, 'Templates')

MEDIA_URL  = '/Media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'Media')

# Conquest Map snapshots are observational, immutable inputs to the public
# read-only API.  The builder publishes this file with os.replace(); web
# requests never fall back to traversing the live solver database.
ATOMICDB_MAP_SNAPSHOT_PATH = os.environ.get(
    'ATOMICDB_MAP_SNAPSHOT_PATH',
    os.path.join(MEDIA_ROOT, 'atomicdb', 'conquest-map-v1.json.gz'),
)

# AtomicDB authoritative tablebase verification.  Paths use the same
# semicolon-separated convention as Client/atomicdb_worker.py --syzygy.
ATOMICDB_TB_PATHS = [
    path for path in os.environ.get(
        'ATOMICDB_TB_PATHS', '/opt/openbench/atomic-syzygy-345/'
    ).split(';') if path
]
ATOMICDB_TB_TRUSTED = [
    username.strip() for username in os.environ.get(
        'ATOMICDB_TB_TRUSTED', 'belzedar'
    ).split(',') if username.strip()
]

INSTALLED_APPS = [
    'atomicdb',
    'OpenBench',
    'OpenBench.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves /static/ with DEBUG=False (the overridden runserver does not
    # accept --insecure); USE_FINDERS avoids needing collectstatic
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',
]

ROOT_URLCONF = 'OpenSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH, ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # OB datagen + AtomicDB share this file: wait out writer bursts
        # instead of raising "database is locked" (DB itself runs WAL)
        'OPTIONS': {'timeout': 30},
    }
}

# Production and CI can exercise the row-lock/CAS path on PostgreSQL without
# maintaining a second settings module. SQLite remains the zero-config local
# default used by existing installations.
if os.environ.get('OPENBENCH_POSTGRES_DB'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['OPENBENCH_POSTGRES_DB'],
        'USER': os.environ.get('OPENBENCH_POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('OPENBENCH_POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('OPENBENCH_POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('OPENBENCH_POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 0,
    }


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
WHITENOISE_USE_FINDERS = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
