# Generated by Django 4.2.30 on 2026-07-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('line_san', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fen', models.TextField()),
                ('eval_cp', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WHITE_WIN', 'White Win'), ('BLACK_WIN', 'Black Win'), ('DRAW', 'Draw')], db_index=True, default='UNKNOWN', max_length=10)),
                ('closure', models.CharField(choices=[('TB', 'Tb'), ('MATE_PV', 'Mate Pv'), ('MINIMAX', 'Minimax'), ('TERMINAL', 'Terminal')], max_length=8, null=True)),
                ('best_move', models.CharField(max_length=8, null=True)),
                ('expanded', models.BooleanField(default=False)),
                ('depth_invested', models.IntegerField(default=0)),
                ('nodes_invested', models.BigIntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('is_wall', models.BooleanField(db_index=True, default=False)),
                ('priority', models.FloatField(db_index=True, default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='atomicdb.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_roots', to='atomicdb.position'),
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_nodes', models.BigIntegerField()),
                ('multipv', models.IntegerField(default=5)),
                ('generation', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('LEASED', 'Leased'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=10)),
                ('machine', models.CharField(default='', max_length=64)),
                ('leased_at', models.DateTimeField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atomicdb.position')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_uci', models.CharField(max_length=8)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edges_in', to='atomicdb.position')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='atomicdb.position')),
            ],
            options={
                'indexes': [models.Index(fields=['child'], name='atomicdb_ed_child_i_ea05a9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('parent', 'move_uci'), name='uniq_parent_move'),
        ),
        migrations.AddConstraint(
            model_name='analysistask',
            constraint=models.UniqueConstraint(fields=('position', 'generation'), name='uniq_task_per_generation'),
        ),
    ]
