# Generated by Django 4.2.30 on 2026-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='won_line',
            field=models.TextField(null=True),
        ),
    ]
