# Generated by Django 4.2.30 on 2026-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0002_position_won_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='last_analysis',
            field=models.JSONField(null=True),
        ),
    ]
