# Generated by Django 4.2.30 on 2026-07-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0003_position_last_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_wall',
        ),
    ]
