# Generated by Django 4.2.30 on 2026-07-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0004_remove_position_is_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='source',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('USER', 'User')], db_index=True, default='AUTO', max_length=4),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atomicdb.position')),
            ],
        ),
    ]
