# Generated by Django 4.2.30 on 2026-07-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0005_analysistask_source_requestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
                ('threads', models.IntegerField(default=0)),
                ('hash_mb', models.IntegerField(default=0)),
                ('os', models.CharField(default='', max_length=64)),
                ('tasks_done', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='workerping',
            constraint=models.UniqueConstraint(fields=('machine', 'user'), name='uniq_worker_machine'),
        ),
    ]
