# Generated by Django 4.2.30 on 2026-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0006_workerping_workerping_uniq_worker_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='time_invested',
            field=models.FloatField(default=0.0),
        ),
    ]
