# Generated by Django 4.2.30 on 2026-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0007_position_time_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='mate_in',
            field=models.IntegerField(null=True),
        ),
    ]
