# Generated by Django 4.2.30 on 2026-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0008_position_mate_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='nodes_searched',
            field=models.BigIntegerField(default=0),
        ),
    ]
