# Generated by Django 4.2.30 on 2026-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0011_worker_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='lease_session',
            field=models.CharField(default='', max_length=64),
        ),
    ]
