# Generated by Django 4.2.30 on 2026-07-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0012_analysistask_lease_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=160)),
                ('root_fen', models.TextField()),
                ('root_key', models.CharField(db_index=True, max_length=64)),
                ('priority_level', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=2)),
                ('evidence_level', models.CharField(choices=[('E0', 'E0'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4')], max_length=2)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('policy_version', models.CharField(max_length=32)),
                ('decay_policy', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['policy_version', 'active'], name='atomic_theory_policy_active')],
                'constraints': [models.UniqueConstraint(fields=('policy_version', 'slug'), name='uniq_theory_policy_slug')],
            },
        ),
        migrations.AddField(
            model_name='analysistask',
            name='threads_at_lease',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='shadow_priority',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='theory_boost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='source',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('THEORY', 'Theory'), ('USER', 'User')], db_index=True, default='AUTO', max_length=6),
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.CharField(db_index=True, max_length=64)),
                ('fen', models.TextField()),
                ('ply', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(default='SEED', max_length=32)),
                ('source_id', models.CharField(max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('artifact_sha256', models.CharField(blank=True, max_length=64)),
                ('path_uci', models.TextField(default='')),
                ('path_sha256', models.CharField(max_length=64)),
                ('provenance_kind', models.CharField(default='STUDY', max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='atomicdb.schedulingcohort')),
            ],
            options={
                'indexes': [models.Index(fields=['position_key', 'cohort'], name='atomic_cohort_position')],
            },
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('cohort', 'position_key', 'source_id', 'path_sha256'), name='uniq_cohort_position_provenance'),
        ),
    ]
