# Generated by Django 4.2.30 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0012_analysistask_lease_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('bucket_start', models.DateTimeField(unique=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('positions_total', models.BigIntegerField(default=0)),
                ('positions_unknown', models.BigIntegerField(default=0)),
                ('positions_closed', models.BigIntegerField(default=0)),
                ('positions_expanded', models.BigIntegerField(default=0)),
                ('engine_nodes_total', models.BigIntegerField(default=0)),
                ('engine_seconds_total', models.FloatField(default=0.0)),
                ('analyses_completed', models.BigIntegerField(default=0)),
                ('tasks_pending', models.BigIntegerField(default=0)),
                ('tasks_leased', models.BigIntegerField(default=0)),
                ('tasks_retried', models.BigIntegerField(default=0)),
                ('lease_retries_total', models.BigIntegerField(default=0)),
                ('recorded_rejections_total',
                 models.BigIntegerField(default=0)),
                ('active_workers', models.BigIntegerField(default=0)),
                ('active_threads', models.BigIntegerField(default=0)),
                ('active_nps', models.BigIntegerField(default=0)),
                ('closure_terminal', models.BigIntegerField(default=0)),
                ('closure_tb', models.BigIntegerField(default=0)),
                ('closure_mate_pv', models.BigIntegerField(default=0)),
                ('closure_minimax', models.BigIntegerField(default=0)),
                ('closure_unclassified', models.BigIntegerField(default=0)),
                ('trust_verified', models.BigIntegerField(default=0)),
                ('trust_andor', models.BigIntegerField(default=0)),
                ('trust_engine', models.BigIntegerField(default=0)),
                ('trust_disputed', models.BigIntegerField(default=0)),
                ('trust_unclassified', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['bucket_start'],
            },
        ),
    ]
