# Generated by Django 4.2.30 on 2026-07-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0014_position_backed_eval'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningNameSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=60)),
                ('comment', models.CharField(blank=True, default='', max_length=280)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=8)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=64)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_suggestions', to='atomicdb.position')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created'], name='atomic_suggestion_state')],
            },
        ),
    ]
