# Generated by Django 4.2.30 on 2026-07-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0015_opening_name_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('summary', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_jobs', to='atomicdb.position')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_job', to='atomicdb.analysistask')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at', 'id'], name='atomic_ingest_ready')],
            },
        ),
    ]
