# Generated by Django 4.2.30 on 2026-07-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0016_ingest_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('goal', models.CharField(choices=[('WHITE_WIN', 'White Win'), ('BLACK_WIN', 'Black Win')], default='WHITE_WIN', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('algorithm_version', models.IntegerField(default=1)),
                ('repertoire_policy', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proof_campaigns', to='atomicdb.position')),
            ],
        ),
        migrations.AddField(
            model_name='analysistask',
            name='engine_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='net_sha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ProofNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.BigIntegerField(default=1)),
                ('dn', models.BigIntegerField(default=1)),
                ('expanded_in_proof', models.BooleanField(default=False)),
                ('selected_child', models.CharField(blank=True, max_length=8, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='atomicdb.proofcampaign')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_nodes', to='atomicdb.position')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'pn'], name='atomic_proof_pn'), models.Index(fields=['campaign', 'dn'], name='atomic_proof_dn')],
            },
        ),
        migrations.AddConstraint(
            model_name='proofnode',
            constraint=models.UniqueConstraint(fields=('campaign', 'position'), name='uniq_proof_node'),
        ),
    ]
