# Generated by Django 4.2.30 on 2026-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0018_default_proof_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='clock_slack',
            field=models.SmallIntegerField(null=True),
        ),
    ]
