# Generated by Django 4.2.30 on 2026-07-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0019_position_clock_slack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='closure',
            field=models.CharField(choices=[('TB', 'Tb'), ('MATE_PV', 'Mate Pv'), ('MINIMAX', 'Minimax'), ('TERMINAL', 'Terminal'), ('SOLVE', 'Solve')], max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='SolveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('WHITE_WIN', 'White Win'), ('BLACK_WIN', 'Black Win')], default='WHITE_WIN', max_length=10)),
                ('budget_nodes', models.BigIntegerField(default=10000000)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('LEASED', 'Leased'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('machine', models.CharField(default='', max_length=64)),
                ('leased_at', models.DateTimeField(null=True)),
                ('lease_heartbeat_at', models.DateTimeField(null=True)),
                ('lease_token', models.CharField(default='', max_length=64)),
                ('lease_session', models.CharField(default='', max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('outcome', models.CharField(blank=True, choices=[('PROVED', 'Proved'), ('DISPROVED', 'Disproved'), ('UNKNOWN', 'Unknown')], default='', max_length=10)),
                ('certificate', models.BinaryField(blank=True, null=True)),
                ('certificate_bytes', models.IntegerField(default=0)),
                ('certificate_nodes', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('advisory_pn', models.BigIntegerField(null=True)),
                ('advisory_dn', models.BigIntegerField(null=True)),
                ('searched_nodes', models.BigIntegerField(default=0)),
                ('elapsed_seconds', models.FloatField(default=0.0)),
                ('solver_build', models.CharField(blank=True, default='', max_length=64)),
                ('arm', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solve_tasks', to='atomicdb.proofcampaign')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_tasks', to='atomicdb.position')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'created'], name='atomic_solve_state')],
            },
        ),
    ]
