# Generated by Django 4.2.30 on 2026-07-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0020_solve_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresssnapshot',
            name='root_dn',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresssnapshot',
            name='root_pn',
            field=models.BigIntegerField(default=0),
        ),
    ]
