# Generated by Django 4.2.30 on 2026-07-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0021_progress_proof_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvetask',
            name='budget_stage',
            field=models.CharField(choices=[('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4')], db_index=True, default='F4', max_length=2),
        ),
        migrations.AddField(
            model_name='solvetask',
            name='telemetry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='source',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('FILL', 'Fill'), ('USER', 'User')], db_index=True, default='AUTO', max_length=4),
        ),
    ]
