# Generated by Django 4.2.30 on 2026-07-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0022_solve_stage_telemetry_and_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvetask',
            name='certificate_format',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='solvetask',
            name='survival_states',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solvetask',
            name='survival_tau',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solvetask',
            name='outcome',
            field=models.CharField(blank=True, choices=[('PROVED', 'Proved'), ('DISPROVED', 'Disproved'), ('UNKNOWN', 'Unknown'), ('DISPROVED_WHITE_WIN', 'Disproved White Win')], default='', max_length=24),
        ),
    ]
