# Generated by Django 4.2.30 on 2026-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0025_opening_name_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='requested_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
