# Generated by Django 4.2.30 on 2026-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0027_campaign_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='route',
            field=models.TextField(blank=True, default=''),
        ),
    ]
