# Generated by Django 4.2.30 on 2026-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0029_request_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='arm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
