# Generated by Django 4.2.30 on 2026-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0030_analysistask_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='proposed_ip',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
