# Generated by Django 4.2.30 on 2026-07-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0031_campaign_proposed_ip'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requestnotification',
            name='uniq_notification_per_task',
        ),
        migrations.AlterField(
            model_name='solvetask',
            name='certificate_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solvetask',
            name='certificate_nodes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solvetask',
            name='survival_states',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='requestnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('task',), name='uniq_notification_per_task'),
        ),
    ]
