# Generated by Django 4.2.30 on 2026-07-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0032_certificate_bigint_and_notification_dedup_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestnotification',
            name='route',
            field=models.TextField(blank=True, default=''),
        ),
    ]
