# Generated by Django 4.2.30 on 2026-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0033_requestnotification_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingnamesuggestion',
            name='suggested_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
