# Generated by Django 4.2.30 on 2026-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0034_openingnamesuggestion_suggested_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analysistask',
            index=models.Index(fields=['requested_by', 'state', 'id'], name='atomic_task_requester'),
        ),
    ]
