# Generated by Django 4.2.30 on 2026-08-15 21:51

"""Whose lane a backed request rides in, when it is not its author's.

Reported live on 15 August (Eclipsia, on a request authored by soothdest).  A
request several people had asked for was charged to its author alone, so with a
saturated author it sat under that author's own backlog, roughly 2690 rows
deep, and backing it moved nothing anybody could see.

``lane_account`` is empty in every row that exists and in every request that
one person asked for, and empty means "the author's lane".  So this migration
moves nothing on deploy: the ordering resolves an empty column to
``requested_by``, which is what it already partitioned by.  The column only
leaves its default when a second person backs a request, which is exactly when
it has something to say.

COST.  One additive column with a constant default, which in PostgreSQL has
been metadata only since 11.  No ``AlterField``, so nothing rebuilds
``atomicdb_analysistask`` (§ 0038, where the reason that matters is written
down).  No index: the ordering reads this column inside a window partition that
sorts the whole waiting band anyway, so an index on it would be paid for on
every write and used on none.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0044_worker_last_result_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='lane_account',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
