# Generated by Django 4.2.30 on 2026-08-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomicdb', '0048_analysistask_arm_rate_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=64, unique=True)),
                ('lifo_queue', models.BooleanField(default=False)),
            ],
        ),
    ]
